services:
  my-proxy:
    build: my-proxy
    ports:
      - "80:80"
    restart: always
  my-frontend:
    build: my-frontend
  my-backend:
    build: my-backend
    env_file:
      - /home/ubuntu/docker-compose-example/.env
    restart: always
